#!/bin/bash -e

# Trim local branches the has no remote (deleted) with manual confirmation.

RED='\033[91m'
BOLD_CYAN='\033[1;96m'
END='\033[0m'

FORCE=false
if [[ "$1" == "--force" ]]; then
    FORCE=true
fi

git fetch --all --prune
BRANCHES=$(git branch -vv | grep gone | tr -d '*' | awk '{$1=$1;print}' | cut -d' ' -f1)

if [[ -z "$BRANCHES" ]]; then
    echo "Nothing to do."
fi

for branch in ${BRANCHES}
do
    echo -ne "Branch ${BOLD_CYAN}${branch}${END}."
    if $FORCE; then
        yesno='y'
        echo -e "\n"
    else
        echo -n " Delete? "
        read yesno
    fi

    if [[ ${yesno} == 'y' ]]; then
       #echo -e "\t\tDelete. git branch -D ${branch}"
       echo -ne "${RED}"
       git branch -D ${branch}
       echo -ne "${END}"
    fi
done
